import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Crimson_Text, EB_Garamond } from 'next/font/google';
import '@styles/globals.css';
import { AuthProvider } from '@app/contexts/AuthContext';
import { CartProvider } from '@app/contexts/CartContext';
import { InlineAdminModeProvider } from '@contexts/InlineAdminModeContext';
import { ToastProvider } from '@contexts/ToastContext';
import { Header } from '@components/layout';
import { InlineAdminEditToggle, AdminDashboardLink } from '@components/features/admin';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const crimsonText = Crimson_Text({
  variable: "--font-crimson-text",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${crimsonText.variable} ${playfairDisplay.variable} ${ebGaramond.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <ToastProvider>
              <InlineAdminModeProvider>
                <Header />
                {children}
                <InlineAdminEditToggle />
                <AdminDashboardLink />
              </InlineAdminModeProvider>
            </ToastProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
