import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Playfair_Display, EB_Garamond } from 'next/font/google';
import '@styles/globals.css';
import { AuthProvider } from './contexts/AuthContext';
import { CartProvider } from './contexts/CartContext';
import { InlineAdminModeProvider } from '@contexts/InlineAdminModeContext';
import { ToastProvider } from '@contexts/ToastContext';
import { Header } from '@components/layout';
import { InlineAdminEditToggle, AdminDashboardLink } from '@components/features/admin';
const geist = localFont({ 
  src: "../../public/fonts/geist/GeistVariable.woff2", 
  variable: "--font-geist" 
});

const geistMono = localFont({ 
  src: "../../public/fonts/geist-mono/GeistMonoVariable.woff2", 
  variable: "--font-geist-mono" 
});

const crimsonText = localFont({
  src: [
    {
      path: '../../public/fonts/crimson-text/CrimsonText-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/crimson-text/CrimsonText-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/crimson-text/CrimsonText-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/crimson-text/CrimsonText-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: "--font-crimson-text",
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} ${crimsonText.variable} ${playfairDisplay.variable} ${ebGaramond.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <ToastProvider>
              <InlineAdminModeProvider>
                <Header />
                {children}
                <InlineAdminEditToggle />
                <AdminDashboardLink />
              </InlineAdminModeProvider>
            </ToastProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
